services:
  web:
    build: ./docker
    container_name: ltw_web
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: fashion_shop
      DB_USER: shop
      DB_PASS: shop_secret
      APP_URL: http://localhost:8000

  db:
    image: mysql:8.0
    container_name: ltw_db
    restart: unless-stopped
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_DATABASE: fashion_shop
      MYSQL_USER: shop
      MYSQL_PASSWORD: shop_secret
      MYSQL_ROOT_PASSWORD: root_secret
    ports:
      - "3308:3306"
    volumes:
      - mysqldata:/var/lib/mysql
      - ./database/mysql_import.sql:/docker-entrypoint-initdb.d/01-import.sql:ro

  adminer:
    image: adminer:latest
    container_name: ltw_adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  mysqldata:
