services:
  web:
    build: ./docker
    container_name: ltw_web
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: fashion_shop
      DB_USER: shop
      DB_PASS: shop_secret
      APP_URL: http://localhost:8000

  db:
    image: postgres:16-alpine
    container_name: ltw_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: fashion_shop
      POSTGRES_USER: shop
      POSTGRES_PASSWORD: shop_secret
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ./database/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql:ro

  adminer:
    image: adminer:latest
    container_name: ltw_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pgdata:
