-- =====================================================================
-- Seed data: Website ban hang thoi trang (PostgreSQL)
-- Tu dong chay sau schema.sql khi container db khoi tao LAN DAU.
-- Mat khau: admin@shop.test / admin123  |  customer / 123456
-- =====================================================================

BEGIN;

-- ---- Nguoi dung ----
-- Hash bcrypt that (admin123 / 123456) — sinh bang password_hash() PHP.
INSERT INTO users (name, email, password_hash, role, phone, address) VALUES
  ('Quan tri vien', 'admin@shop.test', '$2y$10$vcbmDrTl/vr9eYeKveJLmeVigj6jg2FZugFP7Ve5lsERaeCleJHQi', 'admin', '0900000001', 'Van phong ATELIER, Ha Noi'),
  ('Nguyen Van An', 'an@shop.test', '$2y$10$xGVQFDzQQwwaEft29cqpBexzIigt9TmHByPZdeQIRDyohQn.IlcHa', 'customer', '0911111111', '12 Le Loi, Quan 1, TP.HCM'),
  ('Tran Thi Binh', 'binh@shop.test', '$2y$10$xGVQFDzQQwwaEft29cqpBexzIigt9TmHByPZdeQIRDyohQn.IlcHa', 'customer', '0922222222', '34 Cau Giay, Ha Noi');

-- ---- Danh muc ----
INSERT INTO categories (name, slug) VALUES
  ('Áo', 'ao'),
  ('Quần', 'quan'),
  ('Đầm', 'dam'),
  ('Phụ kiện', 'phu-kien'),
  ('Giày', 'giay');

-- ---- San pham (30) ----
INSERT INTO products (category_id, name, slug, description, price, sale_price, brand, status) VALUES
  (1, 'Áo thun cotton basic', 'ao-thun-cotton-basic', 'Áo thun cotton 100% mềm mại, form regular, thoáng mát.', 199000, 159000, 'ATELIER', 'active'),
  (1, 'Áo sơ mi linen dài tay', 'ao-so-mi-linen-dai-tay', 'Sơ mi linen tự nhiên, thoáng khí, hợp công sở lẫn dạo phố.', 459000, NULL, 'ATELIER', 'active'),
  (1, 'Áo polo pique', 'ao-polo-pique', 'Áo polo vải pique co giãn nhẹ, cổ bo gọn gàng.', 329000, 279000, 'Urban', 'active'),
  (1, 'Áo hoodie nỉ bông', 'ao-hoodie-ni-bong', 'Hoodie nỉ bông dày dặn, mũ 2 lớp, túi kangaroo.', 549000, NULL, 'Street', 'active'),
  (1, 'Áo khoác bomber', 'ao-khoac-bomber', 'Bomber chống gió, lớp lót êm, phối đồ năng động.', 759000, 649000, 'Street', 'active'),
  (1, 'Áo len cổ tròn', 'ao-len-co-tron', 'Áo len mịn, giữ ấm tốt, dáng ôm vừa.', 399000, NULL, 'ATELIER', 'active'),
  (1, 'Áo thun oversize', 'ao-thun-oversize', 'Áo thun form rộng trendy, chất cotton dày.', 229000, NULL, 'Street', 'active'),
  (2, 'Quần jean slim fit', 'quan-jean-slim-fit', 'Quần jean co giãn nhẹ, ống slim tôn dáng.', 499000, 399000, 'Denim Co', 'active'),
  (2, 'Quần tây âu công sở', 'quan-tay-au-cong-so', 'Quần tây vải tuyết mưa, ly chính giữa lịch lãm.', 559000, NULL, 'ATELIER', 'active'),
  (2, 'Quần kaki chino', 'quan-kaki-chino', 'Quần kaki chino mềm, dễ phối, đủ màu cơ bản.', 389000, 329000, 'Urban', 'active'),
  (2, 'Quần short kaki', 'quan-short-kaki', 'Short kaki năng động cho mùa hè.', 259000, NULL, 'Urban', 'active'),
  (2, 'Quần jogger nỉ', 'quan-jogger-ni', 'Jogger nỉ bo gấu, lưng chun thoải mái.', 299000, NULL, 'Street', 'active'),
  (2, 'Quần culottes ống rộng', 'quan-culottes-ong-rong', 'Culottes ống rộng thanh lịch, dáng suông.', 359000, 299000, 'ATELIER', 'active'),
  (3, 'Đầm suông linen', 'dam-suong-linen', 'Đầm suông linen nhẹ nhàng, dáng dài qua gối.', 629000, NULL, 'ATELIER', 'active'),
  (3, 'Đầm xòe hoa nhí', 'dam-xoe-hoa-nhi', 'Đầm xòe họa tiết hoa nhí nữ tính.', 689000, 589000, 'Bloom', 'active'),
  (3, 'Đầm body dự tiệc', 'dam-body-du-tiec', 'Đầm ôm body tôn dáng, chất liệu cao cấp.', 899000, NULL, 'Bloom', 'active'),
  (3, 'Đầm maxi đi biển', 'dam-maxi-di-bien', 'Maxi voan mỏng nhẹ, thoáng mát cho mùa hè.', 559000, 459000, 'Bloom', 'active'),
  (3, 'Đầm sơ mi midi', 'dam-so-mi-midi', 'Đầm sơ mi dáng midi thanh lịch, có đai eo.', 649000, NULL, 'ATELIER', 'active'),
  (3, 'Đầm len dệt kim', 'dam-len-det-kim', 'Đầm len dệt kim ôm nhẹ, ấm áp mùa thu đông.', 729000, NULL, 'ATELIER', 'active'),
  (4, 'Túi tote canvas', 'tui-tote-canvas', 'Túi tote vải canvas dày, đựng được nhiều đồ.', 199000, NULL, 'ATELIER', 'active'),
  (4, 'Thắt lưng da bò', 'that-lung-da-bo', 'Thắt lưng da bò thật, khóa kim loại bền.', 349000, 299000, 'Leather', 'active'),
  (4, 'Mũ bucket vải', 'mu-bucket-vai', 'Mũ bucket cotton, vành mềm che nắng tốt.', 159000, NULL, 'Street', 'active'),
  (4, 'Khăn lụa vuông', 'khan-lua-vuong', 'Khăn lụa mềm mượt, họa tiết tinh tế.', 249000, NULL, 'ATELIER', 'active'),
  (4, 'Ví da cầm tay', 'vi-da-cam-tay', 'Ví da nhiều ngăn, thiết kế gọn gàng.', 459000, 399000, 'Leather', 'active'),
  (4, 'Kính mát gọng kim loại', 'kinh-mat-gong-kim-loai', 'Kính mát chống tia UV400, gọng kim loại nhẹ.', 389000, NULL, 'Vision', 'active'),
  (5, 'Giày sneaker trắng', 'giay-sneaker-trang', 'Sneaker trắng tinh basic, dễ phối mọi outfit.', 759000, 659000, 'StepUp', 'active'),
  (5, 'Giày lười da nam', 'giay-luoi-da-nam', 'Giày lười da mềm, đế cao su êm chân.', 689000, NULL, 'Leather', 'active'),
  (5, 'Giày cao gót 7cm', 'giay-cao-got-7cm', 'Cao gót mũi nhọn 7cm thanh lịch.', 629000, 529000, 'Bloom', 'active'),
  (5, 'Giày boots cổ ngắn', 'giay-boots-co-ngan', 'Boots da cổ ngắn, khóa kéo bên hông.', 899000, NULL, 'Leather', 'active'),
  (5, 'Dép sandal quai chéo', 'dep-sandal-quai-cheo', 'Sandal quai chéo êm, hợp đi chơi.', 359000, NULL, 'StepUp', 'active');

-- ---- Anh san pham (picsum.photos, seed theo slug cho on dinh) ----
INSERT INTO product_images (product_id, image_url, is_primary)
SELECT p.id, 'https://picsum.photos/seed/' || p.slug || '/600/750', true FROM products p;
INSERT INTO product_images (product_id, image_url, is_primary)
SELECT p.id, 'https://picsum.photos/seed/' || p.slug || '-2/600/750', false FROM products p;

-- ---- Bien the (size / mau / ton kho) ----
INSERT INTO variants (product_id, size, color, stock, sku) VALUES
  (1, 'S', 'Trắng', 10, 'ao-thun-cotton-basic-s-trang'),
  (1, 'S', 'Xanh navy', 15, 'ao-thun-cotton-basic-s-xanh-navy'),
  (1, 'M', 'Trắng', 13, 'ao-thun-cotton-basic-m-trang'),
  (1, 'M', 'Xanh navy', 18, 'ao-thun-cotton-basic-m-xanh-navy'),
  (1, 'L', 'Trắng', 16, 'ao-thun-cotton-basic-l-trang'),
  (1, 'L', 'Xanh navy', 21, 'ao-thun-cotton-basic-l-xanh-navy'),
  (1, 'XL', 'Trắng', 19, 'ao-thun-cotton-basic-xl-trang'),
  (1, 'XL', 'Xanh navy', 24, 'ao-thun-cotton-basic-xl-xanh-navy'),
  (2, 'S', 'Be', 17, 'ao-so-mi-linen-dai-tay-s-be'),
  (2, 'S', 'Xám', 22, 'ao-so-mi-linen-dai-tay-s-xam'),
  (2, 'M', 'Be', 20, 'ao-so-mi-linen-dai-tay-m-be'),
  (2, 'M', 'Xám', 25, 'ao-so-mi-linen-dai-tay-m-xam'),
  (2, 'L', 'Be', 23, 'ao-so-mi-linen-dai-tay-l-be'),
  (2, 'L', 'Xám', 3, 'ao-so-mi-linen-dai-tay-l-xam'),
  (2, 'XL', 'Be', 26, 'ao-so-mi-linen-dai-tay-xl-be'),
  (2, 'XL', 'Xám', 6, 'ao-so-mi-linen-dai-tay-xl-xam'),
  (3, 'S', 'Xanh navy', 24, 'ao-polo-pique-s-xanh-navy'),
  (3, 'S', 'Đen', 4, 'ao-polo-pique-s-den'),
  (3, 'M', 'Xanh navy', 27, 'ao-polo-pique-m-xanh-navy'),
  (3, 'M', 'Đen', 7, 'ao-polo-pique-m-den'),
  (3, 'L', 'Xanh navy', 5, 'ao-polo-pique-l-xanh-navy'),
  (3, 'L', 'Đen', 10, 'ao-polo-pique-l-den'),
  (3, 'XL', 'Xanh navy', 8, 'ao-polo-pique-xl-xanh-navy'),
  (3, 'XL', 'Đen', 13, 'ao-polo-pique-xl-den'),
  (4, 'S', 'Xám', 6, 'ao-hoodie-ni-bong-s-xam'),
  (4, 'S', 'Trắng', 11, 'ao-hoodie-ni-bong-s-trang'),
  (4, 'M', 'Xám', 9, 'ao-hoodie-ni-bong-m-xam'),
  (4, 'M', 'Trắng', 14, 'ao-hoodie-ni-bong-m-trang'),
  (4, 'L', 'Xám', 12, 'ao-hoodie-ni-bong-l-xam'),
  (4, 'L', 'Trắng', 17, 'ao-hoodie-ni-bong-l-trang'),
  (4, 'XL', 'Xám', 15, 'ao-hoodie-ni-bong-xl-xam'),
  (4, 'XL', 'Trắng', 20, 'ao-hoodie-ni-bong-xl-trang'),
  (5, 'S', 'Đen', 13, 'ao-khoac-bomber-s-den'),
  (5, 'S', 'Be', 18, 'ao-khoac-bomber-s-be'),
  (5, 'M', 'Đen', 16, 'ao-khoac-bomber-m-den'),
  (5, 'M', 'Be', 21, 'ao-khoac-bomber-m-be'),
  (5, 'L', 'Đen', 19, 'ao-khoac-bomber-l-den'),
  (5, 'L', 'Be', 24, 'ao-khoac-bomber-l-be'),
  (5, 'XL', 'Đen', 22, 'ao-khoac-bomber-xl-den'),
  (5, 'XL', 'Be', 27, 'ao-khoac-bomber-xl-be'),
  (6, 'S', 'Trắng', 20, 'ao-len-co-tron-s-trang'),
  (6, 'S', 'Xanh navy', 25, 'ao-len-co-tron-s-xanh-navy'),
  (6, 'M', 'Trắng', 23, 'ao-len-co-tron-m-trang'),
  (6, 'M', 'Xanh navy', 3, 'ao-len-co-tron-m-xanh-navy'),
  (6, 'L', 'Trắng', 26, 'ao-len-co-tron-l-trang'),
  (6, 'L', 'Xanh navy', 6, 'ao-len-co-tron-l-xanh-navy'),
  (6, 'XL', 'Trắng', 4, 'ao-len-co-tron-xl-trang'),
  (6, 'XL', 'Xanh navy', 9, 'ao-len-co-tron-xl-xanh-navy'),
  (7, 'S', 'Be', 27, 'ao-thun-oversize-s-be'),
  (7, 'S', 'Xám', 7, 'ao-thun-oversize-s-xam'),
  (7, 'M', 'Be', 5, 'ao-thun-oversize-m-be'),
  (7, 'M', 'Xám', 10, 'ao-thun-oversize-m-xam'),
  (7, 'L', 'Be', 8, 'ao-thun-oversize-l-be'),
  (7, 'L', 'Xám', 13, 'ao-thun-oversize-l-xam'),
  (7, 'XL', 'Be', 11, 'ao-thun-oversize-xl-be'),
  (7, 'XL', 'Xám', 16, 'ao-thun-oversize-xl-xam'),
  (8, '29', 'Xanh navy', 9, 'quan-jean-slim-fit-29-xanh-navy'),
  (8, '29', 'Đen', 14, 'quan-jean-slim-fit-29-den'),
  (8, '30', 'Xanh navy', 12, 'quan-jean-slim-fit-30-xanh-navy'),
  (8, '30', 'Đen', 17, 'quan-jean-slim-fit-30-den'),
  (8, '31', 'Xanh navy', 15, 'quan-jean-slim-fit-31-xanh-navy'),
  (8, '31', 'Đen', 20, 'quan-jean-slim-fit-31-den'),
  (8, '32', 'Xanh navy', 18, 'quan-jean-slim-fit-32-xanh-navy'),
  (8, '32', 'Đen', 23, 'quan-jean-slim-fit-32-den'),
  (9, '29', 'Xám', 16, 'quan-tay-au-cong-so-29-xam'),
  (9, '29', 'Trắng', 21, 'quan-tay-au-cong-so-29-trang'),
  (9, '30', 'Xám', 19, 'quan-tay-au-cong-so-30-xam'),
  (9, '30', 'Trắng', 24, 'quan-tay-au-cong-so-30-trang'),
  (9, '31', 'Xám', 22, 'quan-tay-au-cong-so-31-xam'),
  (9, '31', 'Trắng', 27, 'quan-tay-au-cong-so-31-trang'),
  (9, '32', 'Xám', 25, 'quan-tay-au-cong-so-32-xam'),
  (9, '32', 'Trắng', 5, 'quan-tay-au-cong-so-32-trang'),
  (10, '29', 'Đen', 23, 'quan-kaki-chino-29-den'),
  (10, '29', 'Be', 3, 'quan-kaki-chino-29-be'),
  (10, '30', 'Đen', 26, 'quan-kaki-chino-30-den'),
  (10, '30', 'Be', 6, 'quan-kaki-chino-30-be'),
  (10, '31', 'Đen', 4, 'quan-kaki-chino-31-den'),
  (10, '31', 'Be', 9, 'quan-kaki-chino-31-be'),
  (10, '32', 'Đen', 7, 'quan-kaki-chino-32-den'),
  (10, '32', 'Be', 12, 'quan-kaki-chino-32-be'),
  (11, '29', 'Trắng', 5, 'quan-short-kaki-29-trang'),
  (11, '29', 'Xanh navy', 10, 'quan-short-kaki-29-xanh-navy'),
  (11, '30', 'Trắng', 8, 'quan-short-kaki-30-trang'),
  (11, '30', 'Xanh navy', 13, 'quan-short-kaki-30-xanh-navy'),
  (11, '31', 'Trắng', 11, 'quan-short-kaki-31-trang'),
  (11, '31', 'Xanh navy', 16, 'quan-short-kaki-31-xanh-navy'),
  (11, '32', 'Trắng', 14, 'quan-short-kaki-32-trang'),
  (11, '32', 'Xanh navy', 19, 'quan-short-kaki-32-xanh-navy'),
  (12, '29', 'Be', 12, 'quan-jogger-ni-29-be'),
  (12, '29', 'Xám', 17, 'quan-jogger-ni-29-xam'),
  (12, '30', 'Be', 15, 'quan-jogger-ni-30-be'),
  (12, '30', 'Xám', 20, 'quan-jogger-ni-30-xam'),
  (12, '31', 'Be', 18, 'quan-jogger-ni-31-be'),
  (12, '31', 'Xám', 23, 'quan-jogger-ni-31-xam'),
  (12, '32', 'Be', 21, 'quan-jogger-ni-32-be'),
  (12, '32', 'Xám', 26, 'quan-jogger-ni-32-xam'),
  (13, '29', 'Xanh navy', 19, 'quan-culottes-ong-rong-29-xanh-navy'),
  (13, '29', 'Đen', 24, 'quan-culottes-ong-rong-29-den'),
  (13, '30', 'Xanh navy', 22, 'quan-culottes-ong-rong-30-xanh-navy'),
  (13, '30', 'Đen', 27, 'quan-culottes-ong-rong-30-den'),
  (13, '31', 'Xanh navy', 25, 'quan-culottes-ong-rong-31-xanh-navy'),
  (13, '31', 'Đen', 5, 'quan-culottes-ong-rong-31-den'),
  (13, '32', 'Xanh navy', 3, 'quan-culottes-ong-rong-32-xanh-navy'),
  (13, '32', 'Đen', 8, 'quan-culottes-ong-rong-32-den'),
  (14, 'S', 'Xám', 26, 'dam-suong-linen-s-xam'),
  (14, 'S', 'Trắng', 6, 'dam-suong-linen-s-trang'),
  (14, 'M', 'Xám', 4, 'dam-suong-linen-m-xam'),
  (14, 'M', 'Trắng', 9, 'dam-suong-linen-m-trang'),
  (14, 'L', 'Xám', 7, 'dam-suong-linen-l-xam'),
  (14, 'L', 'Trắng', 12, 'dam-suong-linen-l-trang'),
  (15, 'S', 'Đen', 8, 'dam-xoe-hoa-nhi-s-den'),
  (15, 'S', 'Be', 13, 'dam-xoe-hoa-nhi-s-be'),
  (15, 'M', 'Đen', 11, 'dam-xoe-hoa-nhi-m-den'),
  (15, 'M', 'Be', 16, 'dam-xoe-hoa-nhi-m-be'),
  (15, 'L', 'Đen', 14, 'dam-xoe-hoa-nhi-l-den'),
  (15, 'L', 'Be', 19, 'dam-xoe-hoa-nhi-l-be'),
  (16, 'S', 'Trắng', 15, 'dam-body-du-tiec-s-trang'),
  (16, 'S', 'Xanh navy', 20, 'dam-body-du-tiec-s-xanh-navy'),
  (16, 'M', 'Trắng', 18, 'dam-body-du-tiec-m-trang'),
  (16, 'M', 'Xanh navy', 23, 'dam-body-du-tiec-m-xanh-navy'),
  (16, 'L', 'Trắng', 21, 'dam-body-du-tiec-l-trang'),
  (16, 'L', 'Xanh navy', 26, 'dam-body-du-tiec-l-xanh-navy'),
  (17, 'S', 'Be', 22, 'dam-maxi-di-bien-s-be'),
  (17, 'S', 'Xám', 27, 'dam-maxi-di-bien-s-xam'),
  (17, 'M', 'Be', 25, 'dam-maxi-di-bien-m-be'),
  (17, 'M', 'Xám', 5, 'dam-maxi-di-bien-m-xam'),
  (17, 'L', 'Be', 3, 'dam-maxi-di-bien-l-be'),
  (17, 'L', 'Xám', 8, 'dam-maxi-di-bien-l-xam'),
  (18, 'S', 'Xanh navy', 4, 'dam-so-mi-midi-s-xanh-navy'),
  (18, 'S', 'Đen', 9, 'dam-so-mi-midi-s-den'),
  (18, 'M', 'Xanh navy', 7, 'dam-so-mi-midi-m-xanh-navy'),
  (18, 'M', 'Đen', 12, 'dam-so-mi-midi-m-den'),
  (18, 'L', 'Xanh navy', 10, 'dam-so-mi-midi-l-xanh-navy'),
  (18, 'L', 'Đen', 15, 'dam-so-mi-midi-l-den'),
  (19, 'S', 'Xám', 11, 'dam-len-det-kim-s-xam'),
  (19, 'S', 'Trắng', 16, 'dam-len-det-kim-s-trang'),
  (19, 'M', 'Xám', 14, 'dam-len-det-kim-m-xam'),
  (19, 'M', 'Trắng', 19, 'dam-len-det-kim-m-trang'),
  (19, 'L', 'Xám', 17, 'dam-len-det-kim-l-xam'),
  (19, 'L', 'Trắng', 22, 'dam-len-det-kim-l-trang'),
  (20, 'Free', 'Đen', 18, 'tui-tote-canvas-free-den'),
  (20, 'Free', 'Be', 23, 'tui-tote-canvas-free-be'),
  (21, 'Free', 'Trắng', 25, 'that-lung-da-bo-free-trang'),
  (21, 'Free', 'Xanh navy', 5, 'that-lung-da-bo-free-xanh-navy'),
  (22, 'Free', 'Be', 7, 'mu-bucket-vai-free-be'),
  (22, 'Free', 'Xám', 12, 'mu-bucket-vai-free-xam'),
  (23, 'Free', 'Xanh navy', 14, 'khan-lua-vuong-free-xanh-navy'),
  (23, 'Free', 'Đen', 19, 'khan-lua-vuong-free-den'),
  (24, 'Free', 'Xám', 21, 'vi-da-cam-tay-free-xam'),
  (24, 'Free', 'Trắng', 26, 'vi-da-cam-tay-free-trang'),
  (25, 'Free', 'Đen', 3, 'kinh-mat-gong-kim-loai-free-den'),
  (25, 'Free', 'Be', 8, 'kinh-mat-gong-kim-loai-free-be'),
  (26, '38', 'Trắng', 10, 'giay-sneaker-trang-38-trang'),
  (26, '38', 'Xanh navy', 15, 'giay-sneaker-trang-38-xanh-navy'),
  (26, '39', 'Trắng', 13, 'giay-sneaker-trang-39-trang'),
  (26, '39', 'Xanh navy', 18, 'giay-sneaker-trang-39-xanh-navy'),
  (26, '40', 'Trắng', 16, 'giay-sneaker-trang-40-trang'),
  (26, '40', 'Xanh navy', 21, 'giay-sneaker-trang-40-xanh-navy'),
  (26, '41', 'Trắng', 19, 'giay-sneaker-trang-41-trang'),
  (26, '41', 'Xanh navy', 24, 'giay-sneaker-trang-41-xanh-navy'),
  (27, '38', 'Be', 17, 'giay-luoi-da-nam-38-be'),
  (27, '38', 'Xám', 22, 'giay-luoi-da-nam-38-xam'),
  (27, '39', 'Be', 20, 'giay-luoi-da-nam-39-be'),
  (27, '39', 'Xám', 25, 'giay-luoi-da-nam-39-xam'),
  (27, '40', 'Be', 23, 'giay-luoi-da-nam-40-be'),
  (27, '40', 'Xám', 3, 'giay-luoi-da-nam-40-xam'),
  (27, '41', 'Be', 26, 'giay-luoi-da-nam-41-be'),
  (27, '41', 'Xám', 6, 'giay-luoi-da-nam-41-xam'),
  (28, '38', 'Xanh navy', 24, 'giay-cao-got-7cm-38-xanh-navy'),
  (28, '38', 'Đen', 4, 'giay-cao-got-7cm-38-den'),
  (28, '39', 'Xanh navy', 27, 'giay-cao-got-7cm-39-xanh-navy'),
  (28, '39', 'Đen', 7, 'giay-cao-got-7cm-39-den'),
  (28, '40', 'Xanh navy', 5, 'giay-cao-got-7cm-40-xanh-navy'),
  (28, '40', 'Đen', 10, 'giay-cao-got-7cm-40-den'),
  (28, '41', 'Xanh navy', 8, 'giay-cao-got-7cm-41-xanh-navy'),
  (28, '41', 'Đen', 13, 'giay-cao-got-7cm-41-den'),
  (29, '38', 'Xám', 6, 'giay-boots-co-ngan-38-xam'),
  (29, '38', 'Trắng', 11, 'giay-boots-co-ngan-38-trang'),
  (29, '39', 'Xám', 9, 'giay-boots-co-ngan-39-xam'),
  (29, '39', 'Trắng', 14, 'giay-boots-co-ngan-39-trang'),
  (29, '40', 'Xám', 12, 'giay-boots-co-ngan-40-xam'),
  (29, '40', 'Trắng', 17, 'giay-boots-co-ngan-40-trang'),
  (29, '41', 'Xám', 15, 'giay-boots-co-ngan-41-xam'),
  (29, '41', 'Trắng', 20, 'giay-boots-co-ngan-41-trang'),
  (30, '38', 'Đen', 13, 'dep-sandal-quai-cheo-38-den'),
  (30, '38', 'Be', 18, 'dep-sandal-quai-cheo-38-be'),
  (30, '39', 'Đen', 16, 'dep-sandal-quai-cheo-39-den'),
  (30, '39', 'Be', 21, 'dep-sandal-quai-cheo-39-be'),
  (30, '40', 'Đen', 19, 'dep-sandal-quai-cheo-40-den'),
  (30, '40', 'Be', 24, 'dep-sandal-quai-cheo-40-be'),
  (30, '41', 'Đen', 22, 'dep-sandal-quai-cheo-41-den'),
  (30, '41', 'Be', 27, 'dep-sandal-quai-cheo-41-be');

-- ---- Don hang mau (de dashboard co so lieu) ----
INSERT INTO orders (user_id, total, status, payment_method, payment_status, shipping_address, phone, customer_name, note, created_at) VALUES
  (2, 717000, 'completed', 'cod', 'paid', '12 Le Loi, Quan 1, TP.HCM', '0911111111', 'Nguyen Van An', 'Giao gio hanh chinh', now() - interval '11 days'),
  (3, 828000, 'completed', 'vnpay', 'paid', '34 Cau Giay, Ha Noi', '0922222222', 'Tran Thi Binh', NULL, now() - interval '10 days'),
  (2, 1217000, 'completed', 'cod', 'paid', '12 Le Loi, Quan 1, TP.HCM', '0911111111', 'Nguyen Van An', NULL, now() - interval '8 days'),
  (3, 589000, 'shipping', 'cod', 'unpaid', '34 Cau Giay, Ha Noi', '0922222222', 'Tran Thi Binh', 'Goi truoc khi giao', now() - interval '6 days'),
  (2, 948000, 'confirmed', 'vnpay', 'paid', '12 Le Loi, Quan 1, TP.HCM', '0911111111', 'Nguyen Van An', NULL, now() - interval '4 days'),
  (3, 259000, 'pending', 'cod', 'unpaid', '34 Cau Giay, Ha Noi', '0922222222', 'Tran Thi Binh', NULL, now() - interval '2 days'),
  (2, 549000, 'cancelled', 'cod', 'unpaid', '12 Le Loi, Quan 1, TP.HCM', '0911111111', 'Nguyen Van An', 'Khach doi y', now() - interval '1 days'),
  (3, 1027000, 'completed', 'vnpay', 'paid', '34 Cau Giay, Ha Noi', '0922222222', 'Tran Thi Binh', NULL, now() - interval '9 days');

-- order_items (order id 1..8 theo thu tu insert tren DB moi); variant_id qua subselect
INSERT INTO order_items (order_id, variant_id, product_name, variant_label, price, quantity) VALUES
  (1, (SELECT id FROM variants WHERE product_id=1 AND size='M' AND color='Trắng' LIMIT 1), 'Áo thun cotton basic', 'M / Trắng', 159000, 2),
  (1, (SELECT id FROM variants WHERE product_id=8 AND size='30' AND color='Đen' LIMIT 1), 'Quần jean slim fit', '30 / Đen', 399000, 1),
  (2, (SELECT id FROM variants WHERE product_id=14 AND size='M' AND color='Be' LIMIT 1), 'Đầm suông linen', 'M / Be', 629000, 1),
  (2, (SELECT id FROM variants WHERE product_id=20 AND size='Free' AND color='Đen' LIMIT 1), 'Túi tote canvas', 'Free / Đen', 199000, 1),
  (3, (SELECT id FROM variants WHERE product_id=26 AND size='40' AND color='Trắng' LIMIT 1), 'Giày sneaker trắng', '40 / Trắng', 659000, 1),
  (3, (SELECT id FROM variants WHERE product_id=3 AND size='L' AND color='Đen' LIMIT 1), 'Áo polo pique', 'L / Đen', 279000, 2),
  (4, (SELECT id FROM variants WHERE product_id=15 AND size='M' AND color='Trắng' LIMIT 1), 'Đầm xòe hoa nhí', 'M / Trắng', 589000, 1),
  (5, (SELECT id FROM variants WHERE product_id=5 AND size='L' AND color='Xanh navy' LIMIT 1), 'Áo khoác bomber', 'L / Xanh navy', 649000, 1),
  (5, (SELECT id FROM variants WHERE product_id=21 AND size='Free' AND color='Đen' LIMIT 1), 'Thắt lưng da bò', 'Free / Đen', 299000, 1),
  (6, (SELECT id FROM variants WHERE product_id=11 AND size='30' AND color='Be' LIMIT 1), 'Quần short kaki', '30 / Be', 259000, 1),
  (7, (SELECT id FROM variants WHERE product_id=4 AND size='XL' AND color='Đen' LIMIT 1), 'Áo hoodie nỉ bông', 'XL / Đen', 549000, 1),
  (8, (SELECT id FROM variants WHERE product_id=28 AND size='39' AND color='Đen' LIMIT 1), 'Giày cao gót 7cm', '39 / Đen', 529000, 1),
  (8, (SELECT id FROM variants WHERE product_id=23 AND size='Free' AND color='Trắng' LIMIT 1), 'Khăn lụa vuông', 'Free / Trắng', 249000, 2);

-- ---- Thanh toan (don 'vnpay' da paid trong seed; cong thanh toan online se chuyen sang SePay sau) ----
INSERT INTO payments (order_id, provider, txn_ref, amount, status) VALUES
  (2, 'vnpay', 'TX1002', 828000, 'success'),
  (5, 'vnpay', 'TX1005', 948000, 'success'),
  (8, 'vnpay', 'TX1008', 1027000, 'success');

-- ---- Danh gia mau ----
INSERT INTO reviews (product_id, user_id, rating, comment) VALUES
  (1, 2, 5, 'Áo mặc rất thích, vải mát, đáng tiền!'),
  (1, 3, 4, 'Chất ổn, form hơi rộng một chút.'),
  (8, 2, 5, 'Quần jean đẹp, ôm vừa vặn.'),
  (14, 3, 5, 'Đầm xinh, vải mềm, sẽ ủng hộ tiếp.'),
  (26, 2, 4, 'Giày êm, màu trắng dễ phối đồ.'),
  (20, 3, 5, 'Túi tote rộng, đựng được nhiều.'),
  (15, 2, 4, 'Đầm hoa dễ thương, đúng mô tả.'),
  (3, 3, 3, 'Áo polo bình thường, tạm ổn.');

COMMIT;
